title: "Deploy a containerized RStudio instance on OCI"
description: ${Messages.solutionsHub.solutions.rstudio.longDescription()}
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
- title: ${Messages.solutionsHub.generalConfig()}
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: ${Messages.solutionsHub.solutions.rstudio.variableGroups.configurationTitle()}
  visible: true  
  variables:
    - rstudio_user
    - rstudio_password
    - show_advanced



- title: ${Messages.solutionsHub.solutions.rstudio.variableGroups.instanceConfigurationTitle()}
  visible: 
      and:
        - show_advanced
  variables:
    - compartment_ocid
    - availability_domain_name 
    - node_shape
    - instance_os
    - linux_os_version
    - generate_public_ssh_key
    - public_ssh_key


- title: ${Messages.solutionsHub.solutions.wordpress.variableGroups.networkConfigurationTitle()}
  visible: 
      and:
        - show_advanced
  variables:
     - vcn
     - vcn_cidr

outputGroups:
- title: ${Messages.solutionsHub.solutions.wordpress.outputGroups.serviceEndpointsTitle()}
  outputs:
    - rstudio_public_ip
- title: ${Messages.solutionsHub.solutions.wordpress.outputGroups.generatedPasswordsTitle()}
  outputs:
    - generated_ssh_private_key

outputs:
  rstudio_public_ip:
    type: link
    title: ${Messages.solutionsHub.solutions.wordpress.outputs.publicIpTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.outputs.publicIpDescription()}
  generated_ssh_private_key:
    title: ${Messages.solutionsHub.solutions.wordpress.outputs.generatedSshPrivateKeyTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.outputs.generatedSshPrivateKeyDescription()}
    type: copyableString
    visible: true

primaryOutputButton: rstudio_public_ip

variables:

  show_advanced:
    type: boolean
    title: ${Messages.solutionsHub.solutions.wordpress.variables.showAdvancedTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.showAdvancedDescription()}
    visible: false
    default: false



  rstudio_user:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.rstudio.variables.rstudioUserTitle()}
    description: ${Messages.solutionsHub.solutions.rstudio.variables.rstudioUserDescription()}
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: true
     

  rstudio_password:
    type: password
    required: true
    title: ${Messages.solutionsHub.solutions.rstudio.variables.rstudioPasswordTitle()}
    description: ${Messages.solutionsHub.solutions.rstudio.variables.rstudioPasswordDescription()}
    pattern: "^(?=.*[!@#%^*_+\\-:?.,\\[\\]\\{\\}])(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?!.*[$\\(\\)]).{8,32}$"
    visible: true
      


# Network
  vcn:
    type: string
    visible: 
      and:
        - show_advanced
    required: true
    title: "VCN name"
    description: "Type VCN name where your RStudio will be deployed."

  vcn_cidr:
    type: string
    visible: 
      and:
        - show_advanced
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN CIDR for your RStudio deployment."

# Instance 
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: 
      and:
        - show_advanced
    title: "Compartment"
    description: "Compartment where your RStudio will be deployed."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: 
      and:
        - show_advanced
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your RStudio will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  node_shape:
    type: oci:core:instanceshape:name
    required: false
    visible: 
      and:
        - show_advanced
    title: "RStudio node shape"
    description: "Choose Instance Shape for RStudio host."
    default: "VM.Standard2.1"
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_os:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS"
    description: "An Operating System that determines the operating system for RStudio host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for RStudio host."
    default: "7.8"
    enum:
      - "7.8"

  label_prefix:
    type: string
    required: false
    visible: false
    title: "RStudio Hostname Prefix"
    description: "Type RStudio Hostname Prefix."

  

  generate_public_ssh_key:
    type: boolean
    title: "Auto generate public ssh key?"
    required: true
    visible: #($show_advanced  == ""Yes"")
      and:
        - show_advanced 

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    description: "In order to access your private nodes with a public SSH key you will need to set up a bastion host (a.k.a. jump box). If using public nodes, bastion is not needed. Left blank to not import keys."
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: 
      and:
        - show_advanced
        - not:
          - generate_public_ssh_key

